name: 'GitHub PR Content Checker'
description: 'Checks PR diff for keywords'
branding:d
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'Github token'
  diffDoesNotContain:
    description: 'String that must not be in the PR diff'
outputs:
  diff:
    description: "Lines added to the PR"

runs:
  using: 'node12'
  main: 'dist/index.js'
