name: Check PR content

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: amitasinha1/Testing-Search-in-PR@main
      with:
        github-token: ${{ github.token }}
        diffDoesNotContain: 'bad string'
          
